M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Thu May 25 07:42:53 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-25T07:42:53+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X12.192Y33.274
X16.002Y33.274
X19.558Y33.306
X23.114Y33.306
T0
M30
